### ISSUE TITLE
Returning HTTP 429 for Warning Status

### ISSUE THREAD

**Issue by pierresouchay** [kadaan/consulate#1]
Hello,

We have similar issues and while we did patch Consul to have checks on a given agent by its serviceId / Name, this approach is also interesting.

I just wonder why you don't keep the same Consul semantics, aka:
* 200 -> all passing
* 429 -> some passing, at least one Warning
* 503 -> at least one critical / maintenance

It would allow to use your tool as a Consul input as well and would avoid having 2 kinds of inputs.

I would for instance allow people to use aliases for Services very easily (see thread [Naming is hard - how to rename services during transitions of service names](https://groups.google.com/forum/#!topic/consul-tool/iKJlYP-wGLw) )

Regards

**Comment by kadaan** [comment]
@pierresouchay Sorry it has taken me so long to see this.  The notification must have gone to junk.  A couple questions:

1. The way Consulate works right now, you can pass `?status=` to the check to adjust what is considered an error or not.  How do you see 429/503 working in that case?  
2. Also, do you have any issue with leaving the other status code that indicate problems with the query (i.e. invalid service name)?

**Comment by kadaan** [comment]
@pierresouchay Also, would you expect it to return 503 if all checks were warnings?

**Comment by kadaan** [comment]
@pierresouchay Fixed in 0.0.2

**Comment by pierresouchay** [comment]
We are using it that way for now in Consul: https://github.com/hashicorp/consul/pull/3551

**Comment by kadaan** [comment]
@pierresouchay I believe 0.0.2 should address your feedback.  By default Consulate returns:
- 429 if there are 1+ passing checks and 1+ warning checks  
- 503 if there are 0 passing checks and 1+ warning checks
- 503 if there are 1+ failing checks

All the status codes can be configured via the command line or the config file.
